# Generated by Django 6.0 on 2025-12-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('NOTICE', '공지사항'), ('FAQ', '자주 묻는 질문'), ('INQUIRY', '1:1문의')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0)),
                ('reply_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='cs_files/')),
            ],
        ),
    ]
